### ISSUE TITLE
自定义动作无法执行

### ISSUE THREAD

**Issue by vriverh** [mingdaocom/private-deployment#12]
自定义动作按钮，工作流只保留了发送站内信，点击按钮后，左下角一直出现“正在执行”，然后就消失了，工作流没有真正执行，查看历史也没有发现执行记录。

**Comment by beckjin** [comment]
我们这边测试下来是正常的。

![](https://user-images.githubusercontent.com/7261408/78098370-75551e00-7411-11ea-8542-65005a591fdc.png)
![](https://user-images.githubusercontent.com/7261408/78098386-83a33a00-7411-11ea-9247-4dcb86b080cd.png)

**Comment by beckjin** [comment]
你可以通过 docker logs `docker ps -a| grep mingdaoyun-community | awk '{print $1}'`  看看执行日志

**Comment by vriverh** [comment]
04:15:32.000 10165711 [pool-2-thread-1] ERROR c.mingdao.reminder.scan.ScanService - start----------
04:15:32.001 10165712 [pool-2-thread-1] INFO  c.mingdao.reminder.scan.ScanService - ??????:  0

**Comment by vriverh** [comment]
我是15分32秒点击执行的

**Comment by beckjin** [comment]
你上面的不是自定义动作的日志。

```
docker logs `docker ps -a| grep mingdaoyun-community | awk '{print $1}'` -f 
```

实时监控以下日志，输出结束后，单独执行一次自定义动作，会有实时输出。

**Comment by vriverh** [comment]
no cache url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/48/h/48/q/90 pathsave url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/48/h/48/q/90 path /data/storage/tmp/1585716279_66379cc0-aacd-483b-8042-7cce5c8f2c02.pngno cache url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/100/h/100/q/90 pathsave url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/100/h/100/q/90 path /data/storage/tmp/1585716279_c4abbdcf-3495-4703-b691-7c03427184f5.pngno cache url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/48/h/48/q/90 pathsave url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/48/h/48/q/90 path /data/storage/tmp/1585716279_00806ca7-a98e-418b-a821-ae96bad604dd.png04:45:02.000 11935711 [pool-2-thread-1] ERROR c.mingdao.reminder.scan.ScanService - start----------
04:45:02.001 11935712 [pool-2-thread-1] INFO  c.mingdao.reminder.scan.ScanService - ??????:  0
no cache url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/48/h/48/q/90 pathsave url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/48/h/48/q/90 path /data/storage/tmp/1585716330_4b9d0b13-0e6d-402f-800d-e72d418ffcd2.pngno cache url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/100/h/100/q/90 pathsave url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/100/h/100/q/90 path /data/storage/tmp/1585716330_d26be416-0758-4c35-816b-dda349ece83e.pngno cache url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/48/h/48/q/90 pathno cache url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/100/h/100/q/90 pathsave url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/48/h/48/q/90 path /data/storage/tmp/1585716330_7ad031e2-a94e-4235-9402-d88af6142d23.pngsave url http://mdy.szwelot.com:80/file/mdpic/UserAvatar/default7.png?watermark/2/text/6buE5rKz/font/5b6u6L2v6ZuF6buR/fontsize/600/fill/d2hpdGU=/dissolve/100/gravity/Center/dx/0/dy/0%7CimageView2/1/w/100/h/100/q/90 path /data/storage/tmp/1585716330_63b688ad-ad89-4771-b1f4-fddde2cedb6b.png04:45:32.000 11965711 [pool-2-thread-1] ERROR c.mingdao.reminder.scan.ScanService - start----------
04:45:32.001 11965712 [pool-2-thread-1] INFO  c.mingdao.reminder.scan.ScanService - ??????:  0
04:45:44.088 11954026 [XNIO-1 task-18] ERROR o.s.k.s.LoggingProducerListener - Exception thrown when sending a message with key='1585716284088' and payload='{"processId":"5e8412a4be07770792bc4511","data":"{\"accountId\":\"1ca7fc65-cd56-4bac-ac5f-1a4cb9b7968...' to topic WorkFlow-Button:
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.

**Comment by beckjin** [comment]
机器什么配置

**Comment by vriverh** [comment]
4核16G，阿里云服务器

**Comment by beckjin** [comment]
安装管理器目录重启下服务  `bash ./service.sh restartall`

**Comment by vriverh** [comment]
上午已经重启过了，问题依然存在，我再试试

**Comment by beckjin** [comment]
如果还是有问题可以帮你到机器上看看，我微信  jonbiao1990

**Comment by beckjin** [comment]
原因：kafka 没启动成功
