### ISSUE TITLE
华为云私有部署

### ISSUE THREAD

**Issue by wakin8848** [mingdaocom/private-deployment#14]
我已经有了华为云的云服务器，想在华为云的应用市场里面选择“明道云私有部署版”镜像来部署，但是又不想重复选择华为的ESC，如何操作？

**Comment by beckjin** [comment]
华为云好像并不支持这么安装，重装系统也没法选择云市场镜像。

你可以通过我们的 [安装教程](https://github.com/mingdaocom/private-deployment/wiki/%E5%8D%95%E6%9C%BA%E6%A8%A1%E5%BC%8F%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85) 来完成，也不算复杂。

**Comment by wakin8848** [comment]
是的，在切换操作系统里面倒是可以选择：公共镜像、私有镜像、共享镜像，我想你们能不能将你的镜像连同操作系统、Docker一起也做成共享镜像发布出来以供选择？


谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"beckjin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月9日(星期四) 下午4:49
收件人:&nbsp;"mingdaocom/private-deployment"<private-deployment@noreply.github.com&gt;;
抄送:&nbsp;"王一"<27202310@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mingdaocom/private-deployment] 华为云私有部署 (#14)





 
华为云好像并不支持这么安装，重装系统也没法选择云市场镜像。
 
你可以通过我们的 安装教程 来完成，也不算复杂。

**Comment by beckjin** [comment]
云市场镜像确实是你提到的全部打包一起的，你可以在切换操作系统内选择明道云私有部署版。

![image](https://user-images.githubusercontent.com/7261408/78878113-71b23e80-7a84-11ea-91f2-7c20b18a05fa.png)
