### ISSUE TITLE
明道云(私有部署)移动终端iOS无法下载

### ISSUE THREAD

**Issue by GavinHwa** [mingdaocom/private-deployment#16]
安装了明道云(私有部署)版本v1.1.0，系统提供了移动终端安装，按照提示扫描进入appstore，手机上一致转圈圈，无法正常下载。

**Comment by WeeTom** [comment]
你好，明道云私有部署App 下载地址是 https://apps.apple.com/cn/app/%E6%98%8E%E9%81%93%E4%BA%91-%E7%A7%81%E6%9C%89%E9%83%A8%E7%BD%B2/id825276156
如果无法打开，一般是网络问题，多尝试几次就好。
