### ISSUE TITLE
你好,我无法注册密钥,请帮看下如何解决呀.

### ISSUE THREAD

**Issue by sccgoo** [mingdaocom/private-deployment#17]
服务器 ID
0afa403691861d3ebc5f05fddd79f17d

进去注册的时候显示 已经注册过了. 但是在产品密钥里面又是空的.

**Comment by beckjin** [comment]
你再重新生成一下。

**Comment by sccgoo** [comment]
如何再生成一次呢?

**Comment by sccgoo** [comment]
好了 解决了 感谢

**Comment by beckjin** [comment]
🤝

**Comment by sccgoo** [comment]
你好, 重新生成后 可以看到密钥了.
但是去部署版粘贴.显示如下:
密钥验证失败, 请重新填写

**Comment by beckjin** [comment]
你加我wx jonbiao1990 我帮看看。
