### ISSUE TITLE
私有化部署如何支持自定义 /data 目录

### ISSUE THREAD

**Issue by GavinHwa** [mingdaocom/private-deployment#18]
目前私有版本安装时目录指定为 /data 目录，这就存在一个问题，现在使用容器、虚拟化等平台，系统本身的目录是有限的，会存在 /data 数据目录耗尽系统盘问题。

如何把 /data 目录修改成自定义的目录地址，比如 /home 下？

**Comment by mhjerryjin** [comment]
目前还不能指定目录或者调整目录安装，建议加个磁盘，mount 到/data 下
