### ISSUE TITLE
私有化部署如何通过nginx绑定域名

### ISSUE THREAD

**Issue by GavinHwa** [mingdaocom/private-deployment#19]
目前私有化部署提供了“端口与访问地址设置” 界面;

现在想实现如下需求：  域名解析到-->公网IP-->NAT到Nginx的VIP-->Nginx配置安装明道私有云的内网地址；

目前按照这种方式配置了，但是系统返回"This application has no configured error view, so you are seeing this as a fallback."

想请问如何解决？

**Comment by beckjin** [comment]
请参考下这个文档：https://github.com/mingdaocom/private-deployment/wiki/%E8%AE%BE%E7%BD%AE%E4%BB%A3%E7%90%86
