### ISSUE TITLE
跨版本升级

### ISSUE THREAD

**Issue by hesiyuan1994** [mingdaocom/private-deployment#20]
升级1.3 和1.4版本需要执行数据库脚本,  如果从1.2直接升级到1.5需要执行脚本吗?

**Comment by beckjin** [comment]
每个版本升级都有对应的文档说明，需要把下图中圈出来的都看下：

![image](https://user-images.githubusercontent.com/7261408/88897706-50b56980-d27e-11ea-9744-eebf61a46125.png)
