### ISSUE TITLE
请问按照教程部署后无法访问IP:38881，安全策略已全部放行

### ISSUE THREAD

**Issue by xie7** [mingdaocom/private-deployment#22]
docker ps里没显示，./service start显示正常用38881访问，但不能登录，是需要安装nginx吗？

**Comment by beckjin** [comment]
不需要安装 nginx ，看下安全策略是否放行正确

**Comment by xie7** [comment]
> 不需要安装 nginx ，看下安全策略是否放行正确

我已经全放行了，还是不能访问，我只想做一个只需要几个账户用的小OA，用的AWS的免费EC2部署的，会不会是机能差，没有运行起来呢？docker ps里没显示有运行的容器。谢谢帮忙看下。

**Comment by beckjin** [comment]
netstat -ntpl 看看 38881 在不在

**Comment by xie7** [comment]
> netstat -ntpl 看看 38881 在不在

没有，只有TCP6 有38881  ，tcp里没有38881

**Comment by beckjin** [comment]
TCP6 对的。 `curl 127.0.0.1:38881`  可以就还是安全策略问题。

**Comment by xie7** [comment]
curl 127.0.0.1:38881  能显示出明道云私有部署版，  但是安全策略我已经都开了呀,

类型 | 协议 | 端口范围 | 源 | 描述 - 可选
-- | -- | -- | -- | --
所有流量 | 全部 | 全部 | 0.0.0.0/0 | -
所有流量 | 全部 | 全部 | ::/0

是要把docker端口映射出来吧？使用docker run -it -d -p 127.0.0.1:38881:38881 <IMAGE ID>/centos:latest /bin/bash 这样可以吗？

**Comment by beckjin** [comment]
> 是要把docker端口映射出来吧？使用docker run -it -d -p 127.0.0.1:38881:38881 /centos:latest /bin/bash 这样可以吗？
不需要。

这种问题可以咨询下 AWS 那边。
