### ISSUE TITLE
helm添加chart仓库报“x509: certificate signed by unknown authority”

### ISSUE THREAD

**Issue by anqixiang** [mingdaocom/private-deployment#24]
执行helm repo add mingdaoyun-charts https://mingdaoyun.tencentcloudcr.com/chartrepo/charts
报错信息如下：
Error: looks like "https://mingdaoyun.tencentcloudcr.com/chartrepo/charts" is not a valid chart repository or cannot be reached: Get https://mingdaoyun.tencentcloudcr.com/chartrepo/charts/index.yaml: x509: certificate signed by unknown authority

**Comment by beckjin** [comment]
我这边试了下，正常的。

![](https://user-images.githubusercontent.com/7261408/98914206-5704e400-2503-11eb-990b-f22c4d6da625.png)

**Comment by beckjin** [comment]
helm repo add mingdaoyun-bj-charts https://mingdaoyun-bj.tencentcloudcr.com/chartrepo/charts

北京这个源你试试。

**Comment by anqixiang** [comment]
用北京的源也不可以，但我用阿里的https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts可以
![image](https://user-images.githubusercontent.com/49931189/99207814-e3602100-27f9-11eb-852a-abe529adc3ca.png)

**Comment by beckjin** [comment]
[mingdaoyun-charts.zip](https://github.com/mingdaocom/private-deployment/files/5543902/mingdaoyun-charts.zip)

**Comment by anqixiang** [comment]
![image](https://user-images.githubusercontent.com/49931189/99209485-3b008b80-27fe-11eb-8ece-e7afb964c482.png)
![image](https://user-images.githubusercontent.com/49931189/99209507-494ea780-27fe-11eb-89f8-8052dc5e1872.png)
![image](https://user-images.githubusercontent.com/49931189/99209526-57042d00-27fe-11eb-8542-7d262c1101dd.png)

**Comment by beckjin** [comment]
环境问题
