### ISSUE TITLE
K8S版创建PVC失败

### ISSUE THREAD

**Issue by anqixiang** [mingdaocom/private-deployment#25]
![image](https://user-images.githubusercontent.com/49931189/99223035-b3774480-281e-11eb-812a-f1556ded8e33.png)
![image](https://user-images.githubusercontent.com/49931189/99223064-beca7000-281e-11eb-8ba2-446bf60b6879.png)

**Comment by beckjin** [comment]
请参考文档 https://github.com/mingdaocom/private-deployment/wiki/Kubernetes 第 7 步中的 `mingdaoyun-data-pv.yaml` ，手动创建 PV
