### ISSUE TITLE
容器镜像中分发的程序泄露了关键信息

### ISSUE THREAD

**Issue by zgcgwin** [mingdaocom/private-deployment#26]
现在私有云部署的镜像能够被随意获取，其中的程序可以被简单的拷贝出来。镜像内的 .net 程序集未做加密处理，可以使用反编译软件进行分析。jar 文件也存在类似的问题。

**Comment by beckjin** [comment]
目前应该并不含敏感信息，另外所有配置信息每个使用客户都可自定义。未来也有开源的计划，所以是否加密问题不大。

**Comment by zgcgwin** [comment]
好的。
