### ISSUE TITLE
邀请邮件发送报错 504 gateway timeout

### ISSUE THREAD

**Issue by kazoku1990** [mingdaocom/private-deployment#3]
系统配置内的邮件服务已经设置，服务器上telnet邮件服务器465端口通。但是通过邀请链接用邮箱注册时，无法发送验证码，报错“504 Gateway Time-out”。

**Comment by beckjin** [comment]
我们将把几种常见的邮件服务配置文档化，相关注意事项会说明。暂时可以使用 qq 邮箱测试，端口 587，密码使用授权码。

**Comment by beckjin** [comment]
请参考：[如何启用发邮件功能](https://github.com/mingdaocom/private-deployment/wiki/%E5%A6%82%E4%BD%95%E5%90%AF%E7%94%A8%E5%8F%91%E9%82%AE%E4%BB%B6%E5%8A%9F%E8%83%BD) 的常用邮箱配置说明部分，如果没列举出当前使用的邮箱类型，留言后我们会继续完善文档。

**Comment by beckjin** [comment]
test

**Comment by kazoku1990** [comment]
QQ邮箱可以
