### ISSUE TITLE
拉取镜像失败

### ISSUE THREAD

**Issue by Kuma01333** [mingdaocom/private-deployment#7]
拉取镜像失败，大部分包显示Pulling fs layer。但是结果仍然会显示镜像创建成功

**Comment by beckjin** [comment]
在启动安装管理程序前，请确保明道云私有部署版的两个 docker 镜像已经拉取成功，镜像整体较大，网速还是需要一定保证的。

可通过  docker images 查看以下两个镜像是否已存在：
```
registry.cn-hangzhou.aliyuncs.com/mdpublic/mingdaoyun-community
registry.cn-hangzhou.aliyuncs.com/mdpublic/mingdaoyun-doc
```

镜像拉取成功按 [单机模式快速安装](https://github.com/mingdaocom/private-deployment/wiki/%E5%8D%95%E6%9C%BA%E6%A8%A1%E5%BC%8F%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85) 第三步开始操作。

**Comment by beckjin** [comment]
test

**Comment by beckjin** [comment]
test1

**Comment by beckjin** [comment]
test2

**Comment by beckjin** [comment]
test3
